server:
  port: 91

spring:
  application:
    name: gk-admin-dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-j6c0gts524084546n5o.mysql.rds.aliyuncs.com:3306/gk-cloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: survey01
    password: Abc!@#45

  data:
    redis:
      database: 11
      host: 47.79.78.66
      port: 6379
      password: Lz121314
      timeout: 6000ms  # 连接超时时长（毫秒）
      connect-timeout: 6000ms  # 连接超时时长（毫秒）
      lettuce:
        pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10     # 连接池中的最大空闲连接
          min-idle: 1       # 连接池中的最小空闲连接

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 是否开启redis缓存  true开启   false关闭
gk:
  redis:
    open: true
  time-zone: Asia/Shanghai
  feign-name: gk-member
  feign-url: http://localhost:8080/survey

#logging:
#  level:
#    root: debug
#    org.springframework: trace